development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= "redis://:#{ENV.fetch('REDIS_PASSWORD', 'default_password')}@#{ENV.fetch('REDIS_HOST', 'localhost')}:6379/1" %>
  channel_prefix: lobsters_production
