default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dummy
  password: dummy
  host: db

development:
  <<: *default
  database: myapp_development
